### PR TITLE
fix(convert): Release versions not migrated in latest release order

### LINKED ISSUE #88: Deployed version of release not migrated
The plugin normally limits the number of versions migrated.  It can happen that it chooses the wrong versions to migrate, and in some cases it can even skip the currently deployed version.

I believe the problem comes from the fact that release versions are sorted alphabetically by the plugin instead of numerically.  So between version 9 and version 10, the plugin believes version 9 is the most recent.

Here is an example when the deployed version is not migrated:
```
$ h2 history nginx
REVISION	UPDATED                 	STATUS    	CHART               	APP VERSION	DESCRIPTION
1       	Wed Nov  6 15:19:52 2019	SUPERSEDED	nginx-ingress-1.24.5	0.26.1     	Install complete
2       	Wed Nov  6 15:19:54 2019	SUPERSEDED	nginx-ingress-1.24.5	0.26.1     	Upgrade complete
3       	Wed Nov  6 15:19:56 2019	SUPERSEDED	nginx-ingress-1.24.5	0.26.1     	Upgrade complete
4       	Wed Nov  6 15:19:58 2019	SUPERSEDED	nginx-ingress-1.24.5	0.26.1     	Upgrade complete
5       	Wed Nov  6 15:20:01 2019	SUPERSEDED	nginx-ingress-1.24.5	0.26.1     	Upgrade complete
6       	Wed Nov  6 15:20:03 2019	SUPERSEDED	nginx-ingress-1.24.5	0.26.1     	Upgrade complete
7       	Wed Nov  6 15:20:05 2019	SUPERSEDED	nginx-ingress-1.24.5	0.26.1     	Upgrade complete
8       	Wed Nov  6 15:20:07 2019	SUPERSEDED	nginx-ingress-1.24.5	0.26.1     	Upgrade complete
9       	Wed Nov  6 15:20:09 2019	SUPERSEDED	nginx-ingress-1.24.5	0.26.1     	Upgrade complete
10      	Wed Nov  6 15:20:11 2019	SUPERSEDED	nginx-ingress-1.24.5	0.26.1     	Upgrade complete
11      	Wed Nov  6 15:23:19 2019	DEPLOYED  	nginx-ingress-1.24.5	0.26.1     	Upgrade complete

$ h2 2to3 convert --release-versions-max 5 nginx 
2019/11/06 15:28:15 Release "nginx" will be converted from Helm v2 to Helm v3.
2019/11/06 15:28:15 [Helm 3] Release "nginx" will be created.
2019/11/06 15:28:15
2019/11/06 15:28:15 NOTE: The max release versions "5" is less than the actual release versions "11".
2019/11/06 15:28:15 This means only "5" of the latest release versions will be converted.
2019/11/06 15:28:15
2019/11/06 15:28:15 [Helm 3] ReleaseVersion "nginx.v5" will be created.
2019/11/06 15:28:15 [Helm 3] ReleaseVersion "nginx.v5" created.
2019/11/06 15:28:15 [Helm 3] ReleaseVersion "nginx.v6" will be created.
2019/11/06 15:28:15 [Helm 3] ReleaseVersion "nginx.v6" created.
2019/11/06 15:28:15 [Helm 3] ReleaseVersion "nginx.v7" will be created.
2019/11/06 15:28:15 [Helm 3] ReleaseVersion "nginx.v7" created.
2019/11/06 15:28:15 [Helm 3] ReleaseVersion "nginx.v8" will be created.
2019/11/06 15:28:15 [Helm 3] ReleaseVersion "nginx.v8" created.
2019/11/06 15:28:15 [Helm 3] ReleaseVersion "nginx.v9" will be created.
2019/11/06 15:28:15 [Helm 3] ReleaseVersion "nginx.v9" created.
2019/11/06 15:28:15 [Helm 3] Release "nginx" created.
2019/11/06 15:28:15 Release "nginx" was converted successfully from Helm v2 to Helm v3.
2019/11/06 15:28:15 Note: The v2 release information still remains and should be removed to avoid conflicts with the migrated v3 release.
2019/11/06 15:28:15 v2 release information should only be removed using `helm 2to3` cleanup and when all releases have been migrated over.

$ h3 list --all-namespaces
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
$ h3 history nginx
REVISION	UPDATED                 	STATUS    	CHART               	APP VERSION	DESCRIPTION
5       	Wed Nov  6 20:20:01 2019	superseded	nginx-ingress-1.24.5	0.26.1     	Upgrade complete
6       	Wed Nov  6 20:20:03 2019	superseded	nginx-ingress-1.24.5	0.26.1     	Upgrade complete
7       	Wed Nov  6 20:20:05 2019	superseded	nginx-ingress-1.24.5	0.26.1     	Upgrade complete
8       	Wed Nov  6 20:20:07 2019	superseded	nginx-ingress-1.24.5	0.26.1     	Upgrade complete
9       	Wed Nov  6 20:20:09 2019	superseded	nginx-ingress-1.24.5	0.26.1     	Upgrade complete
```

### PR DESCRIPTION
**Pull request by hickeyma**
There were scenarios where release versions were not migrated in latest order. Usually occurred with 10 or more release versions and applying the `--release-versions-max` flag.

Fixes #88

### CODE REVIEW

File: pkg/v2/release.go [hunk 1]
```diff
@@ -50,6 +58,8 @@ func GetReleaseVersions(retOpts RetrieveOptions) ([]*rls.Release, error) {
 		return nil, fmt.Errorf("%s has no deployed releases\n", retOpts.ReleaseName)
 	}
 
+	sort.Sort(ByReleaseVersion(releases))
```
Comment (marckhouzam) [inline pkg/v2/release.go]: For the sake of simplicity, is the `reverse` method at the end of this file still needed, now that release are sorted?

**Comment by marckhouzam** [comment]
I can confirm it fixes the bug for me.
Thanks for the quick fix!

File: pkg/v2/release.go (hunk 1 above)
Comment (hickeyma) [reply pkg/v2/release.go]: Good point. Removed.

**Comment by hickeyma** [comment]
Thanks for the review @marckhouzam. Updated and ready for review again.

**Comment by marckhouzam** [comment]
New version works for me.
Thanks!
