### PR TITLE
Read kube-context from environment variable

### LINKED ISSUE #128: Cannot pass --kube-context to plugin
When doing
```
helm 2to3 convert --kube-context lab myrelease
```
the `kube-context` seems to be ignored.
I looked a bit into the code and here is my impression of what is happening.

The `--kube-context` flag is being swallowed by helm and never reaches the plugin.  This is expected behaviour for helm global flags (see https://helm.sh/docs/topics/plugins/#a-note-on-flag-parsing).  

I think the plugin should instead read the `HELM_KUBECONTEXT` variable to figure out if the user has specified a context on the command-line.  This also implies the plugin should not have its own `--kube-context` flag but rely on helm's global one.

Another scenario that probably does not work right now is:
```
HELM_KUBECONTEXT=lab helm 2to3 convert myrelease
```

### PR DESCRIPTION
**Pull request by marckhouzam**
Fixes #128 

Helm parses the `--kube-context` flag and communicates its value to plugins through the `HELM_KUBECONTEXT` variable.  The `--kube-context` flag is never seen by the plugin.

So this PR has the 2to3 plugin read `HELM_KUBECONTEXT` instead of using a flag.
From a user's point of view though, they still use the `--kube-context` flag:
```
helm 2to3 convert --kube-context lab myrelease
```

As for the `--kubeconfig` flag, it is similarly parsed by helm and only communicated to the plugin through the `KUBECONFIG` variable. However the `KUBECONFIG` variable, when set by the user directly, can be a list of paths (colon-seperated).  At the same time, the methods from the helm-plugin-utils package expect a single file when passed a kubeconfig file parameter.  Therefore the `KUBECONFIG` variable cannot be used as the value for field `common.KubeConfig.File`.

helm-plugin-utils parses the `KUBECONFIG` variable properly as long as it reads it from the environment.  Therefore, the second commit of this PR simply leaves `common.KubeConfig.File` empty, to have helm-plugin-utils process the `KUBECONFIG` variable instead.

The user can still use Helm's `--kubeconfig` flag or use the `KUBECONFIG` variable set in the user's environment. E.g.,
```
helm 2to3 convert myrelease --kubeconfig $HOME/.kube/config.lab
```

### CODE REVIEW

File: cmd/environment.go [hunk 1]
```diff
@@ -41,8 +40,6 @@ func (s *EnvSettings) AddBaseFlags(fs *pflag.FlagSet) {
 // AddFlags binds flags to the given flagset.
 func (s *EnvSettings) AddFlags(fs *pflag.FlagSet) {
 	s.AddBaseFlags(fs)
-	fs.StringVar(&s.KubeConfigFile, "kubeconfig", "", "path to the kubeconfig file")
-	fs.StringVar(&s.KubeContext, "kube-context", s.KubeContext, "name of the kubeconfig context to use")
```
Comment (hickeyma) [inline cmd/environment.go]: Is this needed so that it shows the flags for help?

File: cmd/root.go [hunk 2]
```diff
@@ -45,6 +46,8 @@ func NewRootCmd(out io.Writer, args []string) *cobra.Command {
 	flags.Parse(args)
 	settings = new(EnvSettings)
 
+	settings.KubeContext = os.Getenv("HELM_KUBECONTEXT")
```
Comment (hickeyma) [inline cmd/root.go]: Can you add a comment here explaining about how plugin framework handles  `kubeconfig` and `kube-context` flags

Comment (marckhouzam) [reply cmd/root.go]: Done.

File: cmd/environment.go (hunk 1 above)
Comment (marckhouzam) [reply cmd/environment.go]: I hadn't thought of that.  That is a problem.  I guess your suggestion is best.  I'll these line back but won't make them stored in anything real.

Comment (marckhouzam) [reply cmd/environment.go]: So keeping the flags made me think that we may as well support them properly as you had originally done.  The latest version of the PR leaves everything as it was except that it also reads the HELM_KUBECONTEXT variable in case it is set by helm.

So now `--kube-context` and `--kubeconfig` will work both when `2to3` is used as a plugin or directly as a binary.

File: cmd/root.go [hunk 3]
```diff
@@ -45,6 +46,17 @@ func NewRootCmd(out io.Writer, args []string) *cobra.Command {
 	flags.Parse(args)
 	settings = new(EnvSettings)
 
+	// Helm plugins are not passed Helm's global flags but instead must
+	// read the global flag values from each corresponding environment variable.
+	// The below allows to use Helm's --kube-context global flag.
+	if ctx := os.Getenv("HELM_KUBECONTEXT"); ctx != "" {
```
Comment (hickeyma) [inline cmd/root.go]: Should we check first if  `settings.KubeContext` has a value set? I am asking because if run with the binary (not as a plugin), then we would want `settings.KubeContext` to be used instead of `$HELM_KUBECONTEXT`

File: cmd/root.go [hunk 4]
```diff
@@ -45,6 +46,17 @@ func NewRootCmd(out io.Writer, args []string) *cobra.Command {
...
+		settings.KubeContext = ctx
+	}
+
+	// Note that Helm's global --kubeconfig flag has a corresponding KUBECONFIG variable.
```
Comment (hickeyma) [inline cmd/root.go]: Might read better as:
"Note that the plugin's --kubeconfig flag is set by the Helm plugin framework to the KUBECONFIG environment variable instead of being passed into the plugin."

File: cmd/root.go [hunk 5]
```diff
@@ -45,6 +46,17 @@ func NewRootCmd(out io.Writer, args []string) *cobra.Command {
 	flags.Parse(args)
 	settings = new(EnvSettings)
 
+	// Helm plugins are not passed Helm's global flags but instead must
+	// read the global flag values from each corresponding environment variable.
```
Comment (hickeyma) [inline cmd/root.go]: Might read better as:
" Helm plugins are not passed the plugin flags when run with the Helm plugin framework e.g. helm 2to3 convert ...
  The flag values are set to corresponding environment variables instead. The flags are passed as expected when run directly using the binary."

Comment (marckhouzam) [reply cmd/root.go]: How about modifying yours just a bit to clarify that it is Helm's global flags that are not passed to the plugins?  Like so:

"When run with the Helm plugin framework, Helm plugins are not passed the plugin flags that correspond to Helm global flags e.g. helm 2to3 convert --kube-context ...
The flag values are set to corresponding environment variables instead. The flags are passed as expected when run directly using the binary."

File: cmd/root.go (hunk 3 above)
Comment (marckhouzam) [reply cmd/root.go]: I've traced this and when the `--kube-context` flag is set when run with the binary, `settings.KubeContext` is set later on from within the `migrateCmd.Execute()` call in `main.go`.  Therefore it overwrites the value of the `HELM_KUBECONTEXT` variable, as desired.

Thankfully, when called as a plugin, `settings.KubeContext` retains its value during the `migrateCmd.Execute()` because its default value is to be set to itself. See https://github.com/helm/helm-2to3/blob/e898519fe62720e51188bed8a6524e739e6d7ebe/cmd/environment.go#L45
It's like you had already prepared for this case!?!

File: cmd/root.go (hunk 4 above)
Comment (marckhouzam) [reply cmd/root.go]: Done

File: cmd/root.go (hunk 3 above)
Comment (hickeyma) [reply cmd/root.go]: By design of course! :)

File: cmd/root.go (hunk 5 above)
Comment (hickeyma) [reply cmd/root.go]: I think thats good.
